version: "3.9"
services:
  fastapi:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload", "--log-level", "debug", "--loop", "asyncio"]